name: Run ESLint for the client

on:
  pull_request:
    branches:
      - main

jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: cd client && npm ci
      - name: Run ESLint
        run: cd client && npm run lint
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: cd server && npm ci
      - name: Run ESLint
        run: cd server && npm run lint
